name: Deploy to GitHub Pages

on:
  	workflow_dispatch:
    push:
        branches:
            - main # Set this to your default branch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16" # Set this to your project's node version

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist # Set this to your ViteJS output directory
